[package]
name = "oceanmoduler"
version = "0.1.0"
description = "业务建模助手"
authors = ["sea"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "oceanmoduler_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "2.11.2", features = [ "devtools" ] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"  # 用于启动子进程
tauri-plugin-fs = "2"
tauri-plugin-log = "2"
log = "0.4"

tokio = { version = "1", features = ["full"] }
actix-web = "4"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "sqlite"] }
dirs = "6.0.0"
reqwest = { version = "0.13.4", features = ["json"] }
chrono = { version = "0.4", features = ["clock"] }



[features]
default = []




